version: 1

formatters:
    simple:
        format: '%(asctime)s %(name)s %(levelname)-8s %(message)s'
        datefmt: '%Y/%m/%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
        #level: DEBUG
        stream: ext://sys.stderr
    file:
        class : logging.FileHandler
        formatter: simple
        level: DEBUG
        filename: debug.log
        mode: w

#loggers:
#    clogger:
#        level: DEBUG
#        handlers: [console]
#    flogger:
#        level: WARNING
#        handlers: [file]

root:
    level: DEBUG
    handlers: [console, file]

